package com.shosu.orm;

import java.util.Date;

import org.apache.ignite.cache.query.annotations.QuerySqlField;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.springframework.cache.annotation.Cacheable;

// Generated Jan 28, 2015 9:41:06 PM by Hibernate Tools 4.0.0

/**
 * CurrentStatus generated by hbm2java
 */

@Cacheable
@org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class CurrentStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1153541363385420289L;
	@QuerySqlField(index = true)
	private String driverId;
	// private String deviceId; // new field
	// private String deviceType; // new field
	@QuerySqlField(index = true)
	private Boolean selfControlled; // new field
	@QuerySqlField(index = true)
	private Integer companyId;
	@QuerySqlField(index = true)
	private double currentLatitude;
	@QuerySqlField(index = true)
	private double currentLongtitude;
	@QuerySqlField(index = true)
	private String currentStatus;
	// private String currentLocation;
	@QuerySqlField(index = true)
	private String level;
	@QuerySqlField(index = true)
	private String level2;
	@QuerySqlField(index = true)
	private String level3;
	@QuerySqlField(index = true)
	private Date lastModifiedDate;
	@QuerySqlField(index = true)
	private Integer companyGroupId;
	@QuerySqlField(index = true)
	private String languageCode;
	
	@QuerySqlField(index = true)
	private boolean autoOnline;
	
	@QuerySqlField(index = true)
	private boolean newFeild;
	
	
	public CurrentStatus() {
	}



	
	
	public String getDriverId() {
		return driverId;
	}



	

	public boolean isNewFeild() {
		return newFeild;
	}





	public void setNewFeild(boolean newFeild) {
		this.newFeild = newFeild;
	}





	public void setDriverId(String driverId) {
		this.driverId = driverId;
	}





	public Boolean getSelfControlled() {
		return selfControlled;
	}





	public void setSelfControlled(Boolean selfControlled) {
		this.selfControlled = selfControlled;
	}





	public Integer getCompanyId() {
		return companyId;
	}





	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}





	public double getCurrentLatitude() {
		return currentLatitude;
	}





	public void setCurrentLatitude(double currentLatitude) {
		this.currentLatitude = currentLatitude;
	}





	public double getCurrentLongtitude() {
		return currentLongtitude;
	}





	public void setCurrentLongtitude(double currentLongtitude) {
		this.currentLongtitude = currentLongtitude;
	}





	public String getCurrentStatus() {
		return currentStatus;
	}





	public void setCurrentStatus(String currentStatus) {
		this.currentStatus = currentStatus;
	}





	public String getLevel() {
		return level;
	}





	public void setLevel(String level) {
		this.level = level;
	}





	public String getLevel2() {
		return level2;
	}





	public void setLevel2(String level2) {
		this.level2 = level2;
	}





	public String getLevel3() {
		return level3;
	}





	public void setLevel3(String level3) {
		this.level3 = level3;
	}





	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}





	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}





	public Integer getCompanyGroupId() {
		return companyGroupId;
	}





	public void setCompanyGroupId(Integer companyGroupId) {
		this.companyGroupId = companyGroupId;
	}





	public String getLanguageCode() {
		return languageCode;
	}





	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode;
	}





	public boolean isAutoOnline() {
		return autoOnline;
	}





	public void setAutoOnline(boolean autoOnline) {
		this.autoOnline = autoOnline;
	}





	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CurrentStatus))
			return false;
		CurrentStatus castOther = (CurrentStatus) other;
		if (castOther.getDriverId() == null
				&& getDriverId() == null)
			return true;
		if (getDriverId() == null)
			return false;
		return (this.getDriverId().equals(castOther
				.getDriverId()));
	}

	public int hashCode() {
		int result = 17;
		result = 37
				* result
				+ (getDriverId() == null ? 0 : this
						.getDriverId().hashCode());
		return result;
	}		
}
